id: game-brief
version: "1.0"
name: "Game Brief"
description: "Define your game's complete vision and direction"
agent: "game-designer"
estimated_time: "30-45 min"
category: "design"

# Load existing documents for context
input_discovery:
  - name: "project_context"
    patterns: ["project-context.md"]
    strategy: "full"
    required: false
  - name: "brainstorms"
    patterns: ["output/analysis/*brainstorm*.md"]
    strategy: "index"
    required: false

# Output configuration
output:
  path: "output/concept/game-brief.md"
  format: "md"
  update_context: true

# Steps
steps:
  - id: "welcome"
    file: "steps/step-01-welcome.md"
  - id: "identity"
    file: "steps/step-02-identity.md"
  - id: "vision"
    file: "steps/step-03-vision.md"
  - id: "pillars"
    file: "steps/step-04-pillars.md"
  - id: "references"
    file: "steps/step-05-references.md"
  - id: "audience"
    file: "steps/step-06-audience.md"
  - id: "scope"
    file: "steps/step-07-scope.md"
  - id: "review"
    file: "steps/step-08-review.md"

celebrations:
  complete: |
    🎮 Your Game Brief is complete!
    This document defines your game's vision and will guide all future decisions.
    Ready to dive into the GDD?
