id: project-lite
version: "1.0"
name: "Quick Start"
description: "Initialize your project in 2 minutes with core info"
agent: "game-designer"
estimated_time: "2 min"
category: "quick"

# What documents to load before starting
input_discovery:
  - name: "existing_context"
    patterns: ["project-context.md"]
    strategy: "full"
    required: false

# Output configuration
output:
  path: "project-context.md"
  format: "md"
  append: false

# Steps configuration
steps:
  - id: "intro"
    file: "steps/step-01-intro.md"
  - id: "basics"
    file: "steps/step-02-basics.md"
  - id: "complete"
    file: "steps/step-03-complete.md"

# Celebractions
celebrations:
  complete: |
    🎉 Project initialized! Your project-context.md is ready.
    Now you can start with more detailed workflows like Game Brief or brainstorming!
